#!/usr/bin/env ruby

require_relative 'keychain_storage'

def die(msg)
  STDERR.puts msg
  exit 1
end

# TODO DRY /w smudge_secrets_filter
FNAME = ARGV[0]
SECRETS_PATH = File.join(`git rev-parse --show-toplevel`.chomp, '.gitsecrets')
REPO_NAME = [
  `git config filter.secrets.reponame`.chomp,
  File.basename(`git rev-parse --show-toplevel`.chomp)
].reject(&:empty?).first
STDERR.puts "File #{SECRETS_PATH} not found; skipping filter" unless File.exists? SECRETS_PATH

secrets = SecretsMap.new(SECRETS_PATH).for_path(FNAME) if File.exists?(SECRETS_PATH)
keychain = Secrets::KeychainStore.new
matcher = /\b(#{secrets.keys.map {|k| Regexp.quote k}.join('|')})\b/ if secrets

STDIN.each do |line|
  if secrets and line =~ matcher
    name = $1
    key = secrets[name]
    die "error: expected = or : after #{name}" unless line =~ /\b#{name}\s*[=:]\s*(\S+)/
    secret = $1
    secret = $2 if secret =~ /^(['"])(.+)\1$/
    saved_secret = keychain.find(name, key)
    unless secret == saved_secret
      STDERR.puts "#{$?.exitstatus == 0 ? 'Updating' : 'Adding'} keychain entry for #{name}"
      keychain.update(name, key, secret)
    end
    puts line.gsub(secret, "$secret(#{name})")
    STDERR.puts "smudged #{name}" if ENV['DEBUG_GIT_FILTERS']
  else
    puts line
  end
end
